services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gtfs
      POSTGRES_MAX_WAL_SIZE: 1GB
    volumes:
      - ./data/feed-gtfs:/feed-gtfs
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      timeout: 2s

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mynetwork

  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    environment:
      NC_DB: "pg://db:5432?u=postgres&p=1234&d=gtfs"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    volumes:
      - nc_data:/usr/app/data

volumes:
  pgadmin_data:
  nc_data:

networks:
  mynetwork:
    driver: bridge
