version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gtfs
    volumes:
      - ./data/feed-gtfs:/feed-gtfs
      - ./inicializacion/gtfs_schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./load_gtfs_data.sql:/docker-entrypoint-initdb.d/2-load_data.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mynetwork

volumes:
  pgadmin_data:

networks:
  mynetwork:
    driver: bridge
