services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gtfs
      POSTGRES_MAX_WAL_SIZE: 1GB  # Configuración para aumentar el tamaño máximo del WAL

    volumes:
      - ./data/feed-gtfs:/feed-gtfs
      # - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mynetwork

volumes:
  pgadmin_data:

networks:
  mynetwork:
    driver: bridge
